fix: replace clone() with std::slice::from_ref for single element slices
Clippy was flagging inefficient use of .clone() when creating single-element
slices. This change replaces &[item.clone()] with std::slice::from_ref(&item)
which is more efficient as it avoids unnecessary cloning.

Fixed in:
- ark-dlc-sample/src/main.rs: 3 occurrences in DLC transaction building
- ark-sample/src/main.rs: 2 occurrences in VTXO operations

  Checking ark-sample v0.7.0 (/home/runner/work/rust-sdk/rust-sdk/ark-sample)
error: this call to `clone` can be replaced with `std::slice::from_ref`
   --> ark-sample/src/main.rs:232:69
    |
232 |                 let spendable_vtxos = spendable_vtxos(&grpc_client, &[vtxo.clone()], false).await?;
    |                                                                     ^^^^^^^^^^^^^^^ help: try: `std::slice::from_ref(&vtxo)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_ref_to_slice_refs
    = note: `-D clippy::cloned-ref-to-slice-refs` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::cloned_ref_to_slice_refs)]`

error: this call to `clone` can be replaced with `std::slice::from_ref`
   --> ark-sample/src/main.rs:336:69
    |
336 |                 let spendable_vtxos = spendable_vtxos(&grpc_client, &[vtxo.clone()], true).await?;
    |                                                                     ^^^^^^^^^^^^^^^ help: try: `std::slice::from_ref(&vtxo)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_ref_to_slice_refs

error: could not compile `ark-sample` (bin "ark-sample") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>